In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot 

In [34]:
data = pd.read_csv("audi.csv")

In [35]:
data.head(10)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
5    A1  2016  13900    Automatic    32260   Petrol   30  58.9         1.4
6    A6  2016  13250    Automatic    76788   Diesel   30  61.4         2.0
7    A4  2016  11750       Manual    75185   Diesel   20  70.6         2.0
8    A3  2015  10200       Manual    46112   Petrol   20  60.1         1.4
9    A1  2016  12000       Manual    22451   Petrol   30  55.4         1.4

In [36]:
data.shape

(10668, 9)

In [37]:
x = data.drop("price", axis = 1).values
y = data.loc[:, "price"].values

In [38]:
data.isnull().values.any() #when varieties are large use label encoding 

False

In [39]:
x

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [40]:
y

array([12500, 16500, 11000, ..., 17199, 19499, 15999], dtype=int64)

In [41]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:, 0] = le1.fit_transform(x[:, 0])
le2 = LabelEncoder()
x[:, 4] = le2.fit_transform(x[:, 4])

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [2])], remainder = 'passthrough')
x = ct.fit_transform(x)

In [43]:
x

array([[0.0, 1.0, 0.0, ..., 150, 55.4, 1.4],
       [1.0, 0.0, 0.0, ..., 20, 64.2, 2.0],
       [0.0, 1.0, 0.0, ..., 30, 55.4, 1.4],
       ...,
       [0.0, 1.0, 0.0, ..., 150, 49.6, 1.0],
       [1.0, 0.0, 0.0, ..., 150, 47.9, 1.4],
       [0.0, 1.0, 0.0, ..., 150, 47.9, 1.4]], dtype=object)

In [44]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(x)

In [45]:
x

array([[-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
         0.35755001, -0.88021837],
       [ 1.71447913, -0.83282781, -0.71233307, ..., -1.57832278,
         1.03713001,  0.11492465],
       [-0.58326752,  1.2007284 , -0.71233307, ..., -1.42944047,
         0.35755001, -0.88021837],
       ...,
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.09035499, -1.54364705],
       [ 1.71447913, -0.83282781, -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837],
       [-0.58326752,  1.2007284 , -0.71233307, ...,  0.35714729,
        -0.22163749, -0.88021837]])

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [54]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state = 0)
rf.fit(x_train, y_train)

RandomForestRegressor(random_state=0)

In [55]:
pred = rf.predict(x_test)

In [56]:
pred

array([14337.15, 23450.35, 27330.07, ..., 46275.18, 31359.  ,  9929.62])

In [57]:
y_test

array([14998, 21950, 28990, ..., 45995, 30500,  8400], dtype=int64)

In [58]:
from sklearn.metrics import r2_score

In [66]:
r2_score(y_test, pred)

0.9536134841307546

In [69]:
a = np.concatenate((pred.reshape(len(pred), 1), y_test.reshape(len(y_test), 1)), 1)

In [65]:
a

array([[14337.15, 14998.  ],
       [23450.35, 21950.  ],
       [27330.07, 28990.  ],
       ...,
       [46275.18, 45995.  ],
       [31359.  , 30500.  ],
       [ 9929.62,  8400.  ]])

In [72]:
b = pd.DataFrame(a, columns = ["Predictions", "Real values"])

In [74]:
b.head(8)

Predictions  Real values
0  14337.150000      14998.0
1  23450.350000      21950.0
2  27330.070000      28990.0
3  27200.980000      25489.0
4  32250.050000      30950.0
5  28257.477500      30299.0
6  15802.250000      14498.0
7  33246.169527      32000.0